#!/bin/sh
# 首次开机自动执行一次：写入主机名/LAN地址/WiFi名称/默认密码/主题/语言

# 主机名
uci set system.@system[0].hostname='OpenWrt'

# 缩小系统日志内存缓冲区
# 默认64，纯路由+科学上网场景32~48够用，省内存
uci set system.@system[0].log_size='32'



# 删除旧接口，但绝不删除系统自动生成的 device 段
uci -q delete network.lan
uci -q delete network.wan
uci -q delete network.wan6
uci -q delete network.lan_br

# LAN bridge
uci set network.lan_br='device'
uci set network.lan_br.type='bridge'
uci set network.lan_br.name='br-lan'
uci add_list network.lan_br.ports='lan2'
uci add_list network.lan_br.ports='lan3'
uci add_list network.lan_br.ports='lan4'

# LAN
uci set network.lan='interface'
uci set network.lan.device='br-lan'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.6.1/24'
uci set network.lan.netmask='255.255.255.0'

# WAN
uci set network.wan='interface'
uci set network.wan.device='lan1'
uci set network.wan.proto='dhcp'

# WAN6
uci set network.wan6='interface'
uci set network.wan6.device='lan1'
uci set network.wan6.proto='dhcpv6'
uci set network.wan.mtu='1492'
uci commit network

uci set firewall.@defaults[0].flow_offloading='0'
uci set firewall.@defaults[0].flow_offloading_hw='0'
uci commit firewall

# =========================================================
# 默认密码：password（登录/SSH）
# =========================================================

(echo 'password'; sleep 1; echo 'password') | passwd root >/dev/null 2>&1

# =========================================================
# 默认主题：Argon
# =========================================================

uci set luci.main.mediaurlbase='/luci-static/argon'

# 默认语言：简体中文
uci set luci.main.lang='zh_cn'

uci commit system
uci commit network
uci commit luci

exit 0
